name: aoc
version: 0.1.0.0
github: "Blugatroff/adventofcode"

description: Please see the README on GitHub at <https://github.com/Blugatroff/adventofcode>

dependencies:
- base >= 4.7 && < 5
- containers
- either
- heaps
- mtl
- array
- transformers
- loop
- monad-loops

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-unused-matches

default-extensions:
  TupleSections
  LambdaCase
  FlexibleContexts

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
